Build scripts corrected; -n (skip hinting) option added.

diff --git a/source/build_italic b/source/build_italic
--- a/source/build_italic
+++ b/source/build_italic
@@ -18,21 +18,21 @@ delete_tmp () {
   fi
 }
 
-rm -fr build
-mkdir build
-[ ! -d "dist" ] && mkdir dist
-cd build
-
 outputtype="ttf"
 
 instanceparam="-i"
 
 generateufo=true
 
+hinting=true
+
 xslfile="fix_wdth_axis.xsl"
 
-while getopts "csu" options; do
+while getopts "cnsu" options; do
   case "${options}" in
+    n)
+      hinting=false
+      ;;
     u)
       generateufo=false
       ;;
@@ -50,6 +50,16 @@ then
   outputtype=${@:$OPTIND:1}
 fi
 
+if [ $generateufo == true ]
+then
+  rm -fr build
+  mkdir build
+else
+  [ ! -d "build" ] && mkdir build
+fi
+[ ! -d "dist" ] && mkdir dist
+cd build
+
 glyphspkg -o . ../Junicode-Italic.glyphspackage/
 glyphsfile="Junicode-Italic.glyphs"
 
@@ -59,7 +69,7 @@ then
   tmp_d=$(mktemp -d)
   tmp_f=$tmp_d/$glyphsfile
   echo "Saving temporary file ${tmp_f}."
-  sed -e "s/familyName = Junicode Two Beta;/familyName = Junicode Two Beta VF;/" $glyphsfile > $tmp_f
+  sed -e 's/familyName *= *"Junicode *Two *Beta";/familyName = "Junicode Two Beta VF";/' $glyphsfile > $tmp_f
   glyphsfile=$tmp_f
 fi
 
@@ -103,34 +113,57 @@ fi
 if [ $outputtype == "ttf" ]
 then
   cd instance_ttf
-  mkdir hinted
-  for f in Jun*.ttf; do python code_pages.py $f && ttfautohint $f hinted/$f; done
-  cd hinted
-  for f in Jun*.ttf; do python ../../rmfleuroninstructions.py $f; done
-  mv Jun*.ttf ../../../dist/
-  cd ../../../
+  for f in Jun*.ttf; do python ../code_pages.py $f; done
+  if [ $hinting == true ]
+  then
+    mkdir hinted
+    for f in Jun*.ttf; do ttfautohint $f hinted/$f; done
+    cd hinted
+    for f in Jun*.ttf; do python ../../rmfleuroninstructions.py $f; done
+    mv Jun*.ttf ../../../dist/
+    cd ../../../
+  else
+    mv Jun*.ttf ../../dist/
+    cd ../../
+  fi
 fi
 
 if [ $outputtype == "otf" ]
 then
   cd instance_otf
-  mkdir hinted
-  for f in Jun*.otf; do python code_pages.py $f && psautohint -o hinted $f; done
-  mv hinted/Jun*.ttf ../../dist/
-  cd ../../
+  for f in Jun*.otf; do python code_pages.py $f; done
+  if [ $hinting == true ]
+  then
+    mkdir hinted
+    for f in Jun*.otf; do psautohint -o hinted/$f $f; done
+    mv hinted/Jun*.otf ../../dist/
+    cd ../../
+  else
+    mv hinted/Jun*.otf ../dist/
+    cd ../
+  fi
 fi
 
 if [ $outputtype == "variable" ]
 then
   python mkstat.py variable_ttf/Junicode-Italic-fixed-VF.ttf JunicodeTwoBetaVF-Italic.ttf
   python code_pages.py JunicodeTwoBetaVF-Italic.ttf
-  echo "Compiling hints..."
-  xgridfit -q -i JunicodeTwoBetaVF-Italic.ttf -o JunicodeTwoBetaVF-Italic-hinted.ttf JunicodeTwoBetaVF-Italic.yaml
-  if [ $? -eq 0 ]
+  if [ $hinting == true ]
   then
-    cp JunicodeTwoBetaVF-Italic-hinted.ttf ../dist/JunicodeTwoBetaVF-Italic.ttf
-    cd ..
+    echo "Compiling hints..."
+    xgridfit -q -i JunicodeTwoBetaVF-Italic.ttf -o JunicodeTwoBetaVF-Italic-hinted.ttf JunicodeTwoBetaVF-Italic.yaml
+    if [ $? -eq 0 ]
+    then
+      cp JunicodeTwoBetaVF-Italic-hinted.ttf ../dist/JunicodeTwoBetaVF-Italic.ttf
+      cd ..
+    else
+      echo "Hinting failed."
+      cp JunicodeTwoBetaVF-Italic.ttf ../dist/
+    fi
+  else
+    cp JunicodeTwoBetaVF-Italic.ttf ../dist/
   fi
+  cd ..
 fi
 
 delete_tmp
diff --git a/source/build_roman b/source/build_roman
--- a/source/build_roman
+++ b/source/build_roman
@@ -18,23 +18,23 @@ delete_tmp () {
   fi
 }
 
-rm -fr build
-mkdir build
-[ ! -d "dist" ] && mkdir dist
-cd build
-
 outputtype="ttf"
 
 instanceparam="-i"
 
 cleanupafter=true
 
+hinting=true
+
 generateufo=true
 
 xslfile="fix_wdth_axis.xsl"
 
-while getopts "csu" options; do
+while getopts "cnsu" options; do
   case "${options}" in
+    n)
+      hinting=false
+      ;;
     u)
       generateufo=false
       ;;
@@ -52,6 +52,16 @@ then
   outputtype=${@:$OPTIND:1}
 fi
 
+if [ $generateufo == true ]
+then
+  rm -fr build
+  mkdir build
+else
+  [ ! -d "build" ] && mkdir build
+fi
+[ ! -d "dist" ] && mkdir dist
+cd build
+
 glyphspkg -o . ../Junicode-width.glyphspackage/
 glyphsfile="Junicode-width.glyphs"
 
@@ -61,7 +71,7 @@ then
   tmp_d=$(mktemp -d)
   tmp_f=$tmp_d/$glyphsfile
   echo "Saving temporary file ${tmp_f}."
-  sed -e "s/familyName = Junicode Two Beta;/familyName = Junicode Two Beta VF;/" $glyphsfile > $tmp_f
+  sed -e 's/familyName *= *"Junicode *Two *Beta";/familyName = "Junicode Two Beta VF";/' $glyphsfile > $tmp_f
   glyphsfile=$tmp_f
 fi
 
@@ -107,27 +117,41 @@ fi
 if [ $outputtype == "ttf" ]
 then
   cd instance_ttf
-  mkdir hinted
-  for f in Jun*.ttf; do python code_pages.py $f && ttfautohint $f hinted/$f; done
-  cd hinted
-  for f in Jun*.ttf; do python ../../rmfleuroninstructions.py $f; done
-  mkdir fixed
-  for f in Jun*.ttf;
-    do
-      ff="$(basename -- $f)"
-      fff="${ff%.*}"
-      xgridfit -q -m -i $f -o fixed/$f ../../xgf_scripts/$fff.xgf
-  done
-  mv fixed/Jun*.ttf ../../../dist/
-  cd ../../../
+  for f in Jun*.ttf; do python ../code_pages.py $f; done
+  if [ $hinting == true ]
+  then
+    mkdir hinted
+    for f in Jun*.ttf; do ttfautohint $f hinted/$f; done
+    cd hinted
+    for f in Jun*.ttf; do python ../../rmfleuroninstructions.py $f; done
+    mkdir fixed
+    for f in Jun*.ttf;
+      do
+        echo "Adding hints to ${f}."
+        ff="$(basename -- $f)"
+        fff="${ff%.*}"
+        xgridfit -q -m -i $f -o fixed/$f ../../xgf_scripts/$fff.xgf
+    done
+    mv fixed/Jun*.ttf ../../../dist/
+    cd ../../../
+  else
+    mv fixed/Jun*.ttf ../../dist/
+    cd ../../
+  fi
 fi
 
 if [ $outputtype == "otf" ]
 then
   cd instance_otf
-  mkdir hinted
-  for f in Jun*.otf; do python code_pages.py $f && psautohint -o hinted $f; done
-  mv hinted/Jun*.ttf ../../dist/
+  for f in Jun*.otf; do python ../code_pages.py $f; done
+  if [ $hinting == true ]
+  then
+    mkdir hinted
+    for f in Jun*.otf; do psautohint -o hinted/$f $f; done
+    mv hinted/Jun*.otf ../../dist/
+  else
+    mv Jun*.otf ../../dist/
+  fi
   cd ../../
 fi
 
@@ -135,13 +159,21 @@ if [ $outputtype == "variable" ]
 then
   python mkstat.py variable_ttf/Junicode-width-fixed-VF.ttf JunicodeTwoBetaVF-Roman.ttf
   python code_pages.py JunicodeTwoBetaVF-Roman.ttf
-  echo "Compiling hints..."
-  xgridfit -q -i JunicodeTwoBetaVF-Roman.ttf -o JunicodeTwoBetaVF-Roman-hinted.ttf JunicodeTwoBetaVF-Roman.yaml
-  if [ $? -eq 0 ]
+  if [ $hinting == true ]
   then
-    cp JunicodeTwoBetaVF-Roman-hinted.ttf ../dist/JunicodeTwoBetaVF-Roman.ttf
-    cd ..
+    echo "Compiling hints..."
+    xgridfit -q -i JunicodeTwoBetaVF-Roman.ttf -o JunicodeTwoBetaVF-Roman-hinted.ttf JunicodeTwoBetaVF-Roman.yaml
+    if [ $? -eq 0 ]
+    then
+      cp JunicodeTwoBetaVF-Roman-hinted.ttf ../dist/JunicodeTwoBetaVF-Roman.ttf
+    else
+      echo "Hinting failed."
+      cp JunicodeTwoBetaVF-Roman.ttf ../dist/
+    fi
+  else
+    cp JunicodeTwoBetaVF-Roman.ttf ../dist/
   fi
+  cd ..
 fi
 
 delete_tmp
